<?php
/**
 * Created by PhpStorm.
 * User: Alexey
 * Date: 07.08.2018
 * Time: 22:18
 */

namespace Terminal;

use Alexey\Sum;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class SumCommand extends Command
{
    public function configure()
    {
//        parent::configure(); // TODO: Change the autogenerated stub
        $this->setName('sum')
             ->setDescription('Exec sum a + b for terminal.')
            ->addArgument('a', InputArgument::REQUIRED, 'First param')
            ->addArgument('b', InputArgument::REQUIRED, 'Second param');

    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $sum = new Sum();
        $output->writeln($sum->sum(
            $input->getArgument('a'),
            $input->getArgument('b')
        ));
    }
}